[package]
name = "moonrabbit"
version = "0.1.0"
description = "Moonrabbit 桌面客户端（rabbit-web-generic 封装，零依赖 Node 后端）"
authors = ["moonrabbit"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
